homepage/urls.py
from django.urls import path
from . import views

app_name = "homepage"
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('research/', views.ResearchView.as_view(), name='research'),
    path('career/', views.CareerView.as_view(), name='career'),
    path('materials/', views.MaterialsView.as_view(), name='materials'),
    path('blog/', views.BlogView.as_view(), name='blog'),
    # path('b-detail/<int:pk>/', views.BDetailView.as_view(), name='b-detail'),
]

myhomepage/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("homepage.urls")),  # 何にでもマッチすると思うと分かりやすい
]

homepage/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(verbose_name="カテゴリ名", max_length=255)
    slug = models.SlugField(verbose_name="スラッグ", unique=True)

    def __str__(self):
        """
        各カテゴリ毎に格納されている値を返す。
        ex) name = "プログラミング" であったら"プログラミング"
        これを指定することで、一覧表示などの際にカテゴリ名が表示される。
        区別ができる文字列を返すようすると良い。
        """
        return self.name


class Tag(models.Model):
    name = models.CharField(verbose_name="タグ名", max_length=255)
    slug = models.SlugField(verbose_name="スラッグ", unique=True)

    def __str__(self):
        return self.name


class Blog(models.Model):
    title = models.CharField(verbose_name="タイトル", max_length=255)
    subtitle = models.CharField(
        verbose_name="サブタイトル", max_length=255, blank=True, null=True)
    # ForeignKeyフィールドは1対多の関係を表す
    # この場合は1つのカテゴリに対して複数のブログが紐づく
    # blank=Trueを指定すると、何も指定しないことを許す
    category = models.ForeignKey(
        Category, verbose_name="カテゴリ", on_delete=models.DO_NOTHING, blank=True)
    # ManyToManyFieldは多対多の関係を表す
    tags = models.ManyToManyField(Tag, verbose_name="タグ", blank=True)
    content = models.TextField(verbose_name="本文", blank=True, null=True)
    created_at = models.DateTimeField(verbose_name="作成日時", auto_now_add=True)

    class Meta:
        verbose_name_plural = "Blog"
        # レコード取得時に降順（＝新しい順）にソートして返す
        ordering = ["-created_at"]

    def __str__(self):
        return self.title

homepage/forms.py
from django import forms
from django.core.mail import EmailMessage


class ContactForm(forms.Form):
    name = forms.CharField(label="お名前", max_length=255)
    email = forms.EmailField(label="メールアドレス")
    title = forms.CharField(label="件名", max_length=255)
    message = forms.CharField(label="本文", widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields["name"].widget.attrs["class"] = "form-control col-9"
        self.fields["name"].widget.attrs["placeholder"] = "鈴木太郎"

        self.fields["email"].widget.attrs["class"] = "form-control col-11"
        self.fields["email"].widget.attrs["placeholder"] = "hoge@abc.com"

        self.fields["title"].widget.attrs["class"] = "form-control col-11"
        self.fields["title"].widget.attrs["placeholder"] = "経歴について"

        self.fields["message"].widget.attrs["class"] = "form-control col-12"
        self.fields["message"].widget.attrs["placeholder"] = "詐称していないですか？"

    def send_email(self):
        # バリデーション済みの要素を取得
        name = self.cleaned_data["name"]
        email = self.cleaned_data["email"]
        title = self.cleaned_data["title"]
        message = self.cleaned_data["message"]

        # EmailMessageクラスへの引数を作成
        subject = f"連絡：{title}"
        message = f"送信者:{name}\nメールアドレス:{email}\nメッセージ:\n{message}"
        from_email = "admin@example.com"
        to_list = [
            "merioda.seven.24@gmail.com",
        ]
        cc_list = [
            email,
        ]

        # メール送信処理
        message = EmailMessage(subject=subject, body=message,
                               from_email=from_email, to=to_list, cc=cc_list)
        message.send()

homepage/views.py
import logging

from django.urls import reverse_lazy
from django.views import generic
from django.contrib import messages

from .forms import ContactForm
from .models import Blog

# 実行中のファイル名を取得してログを吐く
logger = logging.getLogger(__name__)


class IndexView(generic.TemplateView):  # TemplateViewはテンプレート表示に特化したview
    template_name = 'index.html'


class ContactView(generic.FormView):  # FormViewはフォーム処理に特化したview
    template_name = 'contact.html'
    form_class = ContactForm
    success_url = reverse_lazy("homepage:contact")  # 処理が成功したらリダイレクト

    def form_valid(self, form):  # バリデーションに成功した場合に実行されるメソッド
        form.send_email()
        messages.success(self.request, "メッセージの送信に成功しました。")
        # cleaned_dataはバリデーション済みのデータを指す
        logger.info("E-mail sent by {}".format(form.cleaned_data["name"]))
        return super().form_valid(form)


class ResearchView(generic.TemplateView):
    template_name = "research.html"


class CareerView(generic.TemplateView):
    template_name = "career.html"


class MaterialsView(generic.TemplateView):
    template_name = "materials.html"


class BlogView(generic.ListView):  # ListViewはモデルオブジェクトの一覧を表示することに特化したView
    model = Blog
    # template_name = "blog.html"  まだ実装できていない
    template_name = "constructing.html"
    paginate_by = 5


class BDetailView(generic.DetailView):  # DetailViewはDBの特定のデータ詳細を表示するのに特化したview
    model = Blog
    template_name = "detail.html"
    # pk_url_kwarg = "bnum"   パスコンバータで変数名を「pk」でなくする場合に必要な記述

homepage/templates/base.html
<!--静的ファイルをロード-->
{% load static %}

<!--HTMLのversion宣言。この場合はHTML5となる-->
<!DOCTYPE html>

<!--htmlの内容を示す。必須要素の一つ-->
<html lang="ja">


<head>
    <!--文字コードの宣言-->
    <meta charset="UTF-8">
    <meta name="author" content="Takahiro Suzuki">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="鈴木貴大の個人ホームページ。勉強しながらなのでコメント多めです。">

    <title>{% block title %}{% endblock %}</title>

    <!--    <link rel="icon" type="image/x-icon" href="{% static 'assets/img/favicon.ico' %}" />  -->
    <link rel="icon" type="image/x-icon" href="http://54.92.235.140/static/assets/img/favicon.ico" />

    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js" crossorigin="anonymous"></script>

    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />

    <!-- Core theme CSS (includes Bootstrap)-->
    <!--    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />-->
    <link href="http://54.92.235.140/static/css/styles.css" rel="stylesheet" />

    {% block head %}{% endblock %}
    <!-- my CSS -->
    <link href="http://54.92.235.140/static/css/mystyle.css" rel="stylesheet" />



</head>

<body id="page-top">
    <div id="wrapper">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top bg-dark" id="mainNav">
            <div class="container">
                <a class="navbar-brand js-scroll-trigger" href="#page-top"><img src="{% static 'assets/img/upper_arrow2.svg' %}" alt="" /></a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars ml-1"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav text-uppercase ml-auto">
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'homepage:index' %}">Home</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'homepage:career' %}">Career</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'homepage:research' %}">Research</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'homepage:materials' %}">Materials</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'homepage:blog' %}">Blog</a></li>
                        <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'homepage:contact' %}">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>

        {% block header %}{% endblock %}

        {% if messages %}
        <div class="container mt-5">
            <div class="row">
                <div class="mt-5 w-100">
                    <ul class="messages" style="list-style: none;">
                        {% for message in messages %}
                        <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>
                            {{ message }}
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
        {% endif %}

        {% block contents %}{% endblock %}

        <!-- Footer-->
        <footer class="footer py-4">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-4 text-lg-left">Copyright © Takahiro Suzuki 2020</div>
                    <div class="col-lg-4 my-3 my-lg-0">
                        <a class="btn btn-dark btn-social mx-2" href="https://twitter.com/Takahiro2525vdo" target="_blank"><i class="fab fa-twitter"></i></a>
                        <a class="btn btn-dark btn-social mx-2" href="https://www.linkedin.com/in/takahiro-suzuki-0331/" target="_blank"><i class="fab fa-linkedin-in"></i></a>
                        <a class="btn btn-dark btn-social mx-2" href="https://github.com/tkp0331" target="_blank"><i class="fab fa-github"></i></a>
                    </div>
                </div>
            </div>
        </footer>


        <!-- Bootstrap core JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script>
        <!-- Third party plugin JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
        <!-- Contact form JS-->
        <script src="assets/mail/jqBootstrapValidation.js"></script>
        <script src="assets/mail/contact_me.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </div>
</body>

</html>

homepage/templates/blog.html
{% extends "base.html" %}
{% load static %}

{% block title %}とある東北大院生のHP|Blog{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/clean-blog.min.css' %}">
{% endblock %}

{% block contents %}

<div class="mt-5"></div>
<div class="mt-5"></div>

{% for blog in blog_list %}
<!-- blog_list == object_list -->
<div class="post-preview border-bottom pb-3 mb-1">
    <a href="{% url 'homepage:b-detail' blog.pk %}">
        <h5 class="post-title">
            {{ blog.title }}
        </h5>
        {% if blog.subtitle %}
        <h5 class="post-subtitle">
            {{ blog.subtitle }}
            {% else %}
            <b>no subtitle</b>
            {% endif %}
        </h5>
    </a>
</div>
{% empty %}
<h5>ブログはまだありません</h5>
{% endfor %}


<!-- ここからページネーションの処理 -->

<!-- ページネーションが可能かどうかの判定 -->
{% if is_paginated %}

<!-- このままではブログ記事にベタっと張り付いてしまうのでcenter指定をする -->
<ul class="pagination justify-content-center mt-5">

    <!-- 前ページが存在するかどうか判定 -->
    {% if page_obj.has_previous %}
    <li class="page-item">
        {# ?以降はクエリ文字列（クエリストリング）#}
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            <span aria-hidden="true">&laquo;</span>
        </a>
    </li>
    {% endif %}

    <!-- ページ数の表示 -->

    {% for page_num in page_obj.paginator.page_range %}

    {% if page_obj.number == page_num %}

    <li class="page-item active"><a class="page-link" href="#">{{ page_num }}</a></li>

    {% else %}

    <li class="page-item"><a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a></li>
    {% endif %}
    {% endfor %}

    <!-- 次ページへのリンク -->
    {% if page_obj.has_next %}
    <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
            <span aria-hidden="true">&raquo;</span>
        </a>
    </li>
    {% endif %}
</ul>
{% endif %}

{% endblock %}

homepage/templates/career.html
{% extends "base.html" %}

{% block title %}とある東北大院生のHP|Career{% endblock %}

{% block contents %}

{% include 'career_parts/resume.html' %}

{% include 'career_parts/awards.html' %}

{% include 'career_parts/can_do_it_alittle.html' %}

{% include 'career_parts/can_do.html' %}

{% endblock %}

homepage/templates/career_parts/awards.html
<div class="container-fluid mt-5">
    <div class="row border-bottom mt-5 mb-2">
        <h5 class="mt-4">受賞など</h5>
    </div>
    <div class="row">
        <table class="table table-borderless table-striped">
            <tr>
                <th>時期</th>
                <th>内容</th>
            </tr>
            <tr>
                <td>2020年1月</td>
                <td>TOEIC 795点取得</td>
            </tr>
            <tr>
                <td>2020年3月</td>
                <td>工学部長賞 受賞</td>
            </tr>
            <tr>
                <td>2020年3月</td>
                <td>東北大学 ３年早期卒業</td>
            </tr>
            <tr>
                <td>2020年7月</td>
                <td><a href="https://www.iyasaka-zaidan.org/" target="_blank">いやさか奨学金</a> 奨学生採用</td>
            </tr>
        </table>
    </div>
</div>

homepage/templates/career_parts/can_do.html
<div class="container-fluid mt-5">
    <div class="row border-bottom mt-5 mb-2">
        <h5 class="mt-4">出来ること</h5>
    </div>
    <ul style="column-count: 2;">
        <li>ブラック環境で生き抜くこと</li>
        <li>毎日Monsterを飲むこと</li>
        <li>眠さを我慢すること</li>
        <li>毎日の睡眠時間を6時間以内に収めること</li>
        <li>お得にお買い物すること</li>
        <li>10時間以上連続してアニメを見ること</li>
    </ul>
</div>

homepage/templates/career_parts/can_do_it_alittle.html
<div class="container-fluid mt-5">
    <div class="row border-bottom mt-5 mb-2">
        <h5 class="mt-4">ちょっと出来ること</h5>
    </div>
    <ul style="column-count: 2;">
        <li>HTML</li>
        <li>CSS</li>
        <li>bootstrap</li>
        <li>JavaScript</li>
        <li>C</li>
        <li>C#</li>
        <li>Java</li>
        <li>Unity</li>
        <li>LaTex</li>
        <li>python</li>
        <li>Django</li>
        <li>画像処理</li>
        <li>OpenCV-python</li>
        <li>機械学習</li>
        <li>pandas</li>
        <li>numpy</li>
        <li>scikit-learn</li>
        <li>深層学習</li>
        <li>pytorch</li>
        <li>グラフ理論</li>
        <li>networkx</li>
        <li>スパースモデリング</li>
        <li>D-wave</li>
        <li>統計</li>
        <li>線形代数</li>
        <li>数理最適化</li>
    </ul>
</div>

homepage/templates/career_parts/resume.html
<div class="container-fluid mt-5">
    <div class="row border-bottom mt-5 mb-2">
        <h5 class="mt-4">これまでの人生</h5>
    </div>
    <div class="row">
        {# 取り敢えずstripedにしたが、シックリ来なかったらtable-stripedを削除する #}
        <table class="table table-borderless table-striped">
            <tr>
                <th>時期</th>
                <th>内容</th>
            </tr>
            <tr>
                <td>2017年4月</td>
                <td>東北大学 工学部 電気情報物理工学科 入学（一般合格）</td>
            </tr>
            <tr>
                <td>2019年4月</td>
                <td><a href="https://hacarus.com/ja/" target="_blank">株式会社HACARUS</a> にてインターンシップ開始</td>
            </tr>
            <tr>
                <td>2019年5月</td>
                <td><a href="http://www.sb.ecei.tohoku.ac.jp/" target="_blank">木下・大林・西研究室</a>に配属される</td>
            </tr>
            <tr>
                <td>2020年3月</td>
                <td>東北大学 工学部 電気情報物理工学科 卒業（３年早期卒業）</td>
            </tr>
            <tr>
                <td>2020年4月</td>
                <td>東北大学 大学院 情報科学研究科 応用情報科学専攻 入学（早期卒業生枠）</td>
            </tr>
            <tr>
                <td>2020年4月</td>
                <td><a href="https://www.smapip.is.tohoku.ac.jp/index.html" target="_blank">田中・大関研究室</a>に配属される</td>
            </tr>
            <tr>
                <td>2020年9月</td>
                <td>楽天インターンシップ<a href="https://commerce-engineer.rakuten.careers/careers/graduates/internship/summer-short" target="_blank">二子玉川夏の陣2020</a>に参加</td>
            </tr>
        </table>
    </div>
</div>

homepage/templates/constructing.html
{% extends "base.html" %}

{% block title %}とある東北大院生のHP|NowConstructing{% endblock %}

{% load static %}
{% block contents %}

<div class="container-fluid mt-5">
    <div class="row mt-5">
        <h1 class="mt-5 text-center col-sm-12">Now Constructing...</h1>
        <img src="{% static 'assets/img/constructing.png' %}" alt="Image not found." class="mx-auto d-block">
    </div>
</div>
{% endblock %}

homepage/templates/contact.html
{% extends 'base.html' %}

{% block title %}とある東北大院生のHP|Contact{% endblock %}

{% block contents %}

<div class="container mt-5">
    <div class="row mt-5">
        <div class="col-lg-12">
            <p class="comment">※お勉強のために作ってみましたが、これじゃなくてもTwitterのDMとかで構いません笑</p>
        </div>
    </div>
    <div class="row">
        <form method="post">
            {% csrf_token %}

            {{ form.non_field_errors }}

            {% for field in form %}
            <div class="form-group row">
                {# label要素を使うと、フォーム中の項目名と部品が紐づく #}
                {# field.id_for_labelを使うと、部品のidを取得でき、それをforに指定することで項目名と部品を紐付け出来る #}
                <label for="{{ field.id_for_label }}" class="col-sm-4 col-form-label">
                    <strong>{{ field.label_tag }}</strong>
                </label>
                <div class="col-sm-8">
                    {{ field }}
                    {{ field.errors }}
                </div>
            </div>
            {% endfor %}

            <div class="offset-sm-4 col-sm-8">
                <button class="btn btn-primary" type="submit">送信</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

homepage/templates/detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}とある東北大院生のHP|BlogDetail{% endblock %}

{% block contents %}

<div class="mt-5"></div>
<div class="mt-5"></div>

<div class="container-fluid">

    <div class="row mt-3 mb-2">
        <div class="col-3">
            <b>タイトル</b>
        </div>
        <div class="col-9">
            {{ object.title }}
        </div>
    </div>

    <div class="row mb-2">
        <div class="col-3">
            サブタイトル
        </div>
        <div class="col-9">
            {{ object.subtitle }}
        </div>
    </div>

    <div class="row mb-2">
        <div class="col-3">
            <b>内容</b>
        </div>
        <div class="col-9">
            {{ object.content }}
        </div>
    </div>
</div>


{% endblock %}

homepage/templates/index.html
{% extends 'base.html' %}

{% load static %}

{% block title %}とある東北大院生のHP{% endblock %}

{% block header %}

<header class="masthead">
    <div class="container">
        <div class="masthead-subheading">Welcome To My Home Page!</div>
        <div class="masthead-heading text-uppercase">とある東北大院生のHP</div>
    </div>
</header>

{% endblock %}

{% block contents %}
<section>
    <div class="container-fluid">
        <div class="row align-items-center">
            <div class="col-lg-6 order-lg-2">
                <div class="row align-items-center">
                    <div class="col-lg-12 box">
                        <div class="p-2">
                            <h5 class="display-5">ちょっと自己紹介</h5>
                            <p>
                                東北大大学院情報科学研究科Mの学生。<br>
                                機械学習や画像処理を良くやってたが、最近Web系に目覚めた。絶賛勉強中です（2020/10/26）<br>
                                アニメや坂道系アイドルが好きで、風呂上がりにお酒呑みながら動画鑑賞することが楽しみ。
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-12 box">
                    <h5 class="display-5">最近ハマっている動画</h5>
                    <p>王道ですが、LiSA。良いですねぇ。。。</p>
                    <iframe width="440" height="200" src="https://www.youtube.com/embed/4DxL6IKmXx4" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                </div>
            </div>
            <div class="col-lg-6 order-lg-1">
                <div class="p-5">
                    <img class="img-fluid rounded-pill" src="{% static 'assets/img/myself/01.jpg' %}" alt="Image not found.">
                </div>
            </div>
        </div>
    </div>
</section>
<section>
    <div class="container">
        <h3><img src="{% static 'assets/img/new023_05.gif' %}" alt="Image not found.">更新情報</h3>
        <div class="border">
            <ul class="list-group list-group-flash">
                <li class="list-group-item">これを作成中。。。</li>
                <li class="list-group-item">結構大変。。。</li>
            </ul>
        </div>
    </div>
</section>
{% endblock %}

homepage/templates/materials.html
{% extends 'base.html' %}

{% block title %}とある東北大院生のHP|Materials{% endblock %}

{% block contents %}

{% include 'materials_parts/slides.html' %}

{% include 'materials_parts/colab_notebooks.html' %}

{% endblock %}

homepage/templates/materials_parts/colab_notebooks.html
<div class="container-fluid mt-5">
    <div class="row border-bottom mt-5">
        <h5>Google colaboratory</h5>
    </div>
    <table class="table table-borderless">
        <tr>
            <th>タイトル</th>
            <th>分類</th>
            <th>作成時期</th>
            <th>簡単な内容説明</th>
        </tr>
        <tr>
            <td><a href="https://colab.research.google.com/drive/1cSCwwzhg2VRLAi1tkWiuSyIgvx2RK0j9?usp=sharing" target="_blank">networkx-hands-on</a></td>
            <td>グラフ理論</td>
            <td>2020年10月</td>
            <td>Pythonでグラフ理論を扱うことが出来る代表的ライブラリnetworkxのハンズオン</td>
        </tr>
        <tr>
            <td><a href="https://colab.research.google.com/drive/1RU2l9ADR4urgOYAwDHFHkgxarkbusu_2?usp=sharing" target="_blank">pythonで体感する正規表現</a></td>
            <td>正規表現</td>
            <td>2020年4月</td>
            <td>Pythonで正規表現を処理するためにはどうするのか、そもそも正規表現とは何かを手を動かしながら学ぶ。<a href="#regular-expression">スライド</a>も参照。</td>
        </tr>
    </table>
</div>

homepage/templates/materials_parts/slides.html
<div class="container-fluid mt-5">
    <div class="row border-bottom mt-5">
        <h5 class="mt-4">スライド資料</h5>
    </div>
    <table class="table table-borderless">
        <tr>
            <th>タイトル</th>
            <th>分類</th>
            <th>作成時期</th>
            <th>簡単な内容説明</th>
        </tr>
        <tr>
            <td><a href="https://www.slideshare.net/ssuser6d6ed8/ss-239033744" target="_blank">ベンダーズの分解法</a></td>
            <td>数理最適化/分解法</td>
            <td>2020年10月</td>
            <td>異なるクラスが混合している最適化問題に対して、それらを分解することにより解を得ようとするアプローチ</td>
        </tr>

        <tr>
            <td id="regular-expression"><a href="https://drive.google.com/file/d/1GLTZVax3D3UVtmITVXeXoKTtmZFtyzMy/view?usp=sharing" target="_blank">正規表現</a></td>
            <td>プログラミング</td>
            <td>2020年４月</td>
            <td>基礎的な正規表現をスライドにまとめたもの。なお、こちらは<b>共同作成したもの</b>です。</td>
        </tr>
        <tr>
            <td><a href="https://docs.google.com/presentation/d/1e-po7Cauq9x1De-QC2yqJ_kNUxsZnVUGG5kvx1ZWfaI/edit?usp=sharing" target="_blank">リーダブルコードを理解していこう-1章-</a></td>
            <td>プログラミング</td>
            <td>2020年3月</td>
            <td>真に目指すべきコードの書き方とはどのようなものか、という問いに対して１つの答えを与えてくれる書籍の1章をまとめた。輪読会用の資料。</td>
        </tr>
    </table>
</div>

homepage/templates/research.html
{% extends 'base.html' %}

{% load static %}

{% block title %}とある東北大院生のHP|Research{% endblock %}

{% block contents %}
<div class="container-fluid mt-5">
    <div class="row border-bottom mt-5 mb-2">
        <h5 class="mt-4">卒業研究</h5>
    </div>
    <div class="row">
        <table class="table table-borderless">
            <tr>
                <th>タイトル</th>
                <td>MRIデータによるグリオーマ有無識別器の構築</td>
            </tr>
            <tr>
                <th>内容</th>
                <td>機械学習を用いてMRI画像中にグリオーマが存在するかどうかを判定する識別機を構築</td>
            </tr>
            <tr>
                <th>スライド</th>
                <td><a href="{% static 'assets/pdf/B3_final_SuzukiTakahiro.pdf' %}" target="_blank">英語版</a></td>
            </tr>
            <tr>
                <th>
                    コメント
                </th>
                <td>
                    「初~~~」がてんこ盛りな卒業研究でした。苦労話は沢山あります。お酒の席で話したい。<br>
                    特に、人データなのでデータセットを探すのが大変だった記憶があります。
                </td>
            </tr>
        </table>
    </div>
</div>

<div class="container-fluid">
    <div class="row border-bottom mt-5 mb-2">
        <h5>修論</h5>
    </div>
    <div class="row">
        <table class="table table-borderless">
            <tr>
                <th>タイトル</th>
                <td>未定</td>
            </tr>
            <tr>
                <th>内容</th>
                <td>古典計算機と量子計算機を併用したハイブリッド最適化アルゴリズムについて研究中</td>
            </tr>
            <tr>
                <th>スライド</th>
                <td><a href="#!">None</a></td>
            </tr>
            <tr>
                <th>
                    コメント
                </th>
                <td>
                    就活とインターン、研究と3つの重たいことを並行に進めなくてはならず、大変です。。。
                </td>
            </tr>
        </table>
    </div>
</div>
{% endblock %}